In [6]:
import numpy as np

In [7]:
x = np.array([1,2,3])     
#note how we use both paranthesis and square brackets
x

array([1, 2, 3])

In [15]:
# use of shape for 2-d arrays
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print('------- A blank line ----------')
m.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------- A blank line ----------


(3, 3)

In [21]:
# iterations

m = np.arange(0,30,2)
print(m)

#  syntax : arange(start,stop,steps)
# note stop, denotes (<) and not (<=)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [23]:
m.reshape(3,5)

# use reshape to resize the array to a conformable type

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [28]:
# Equally spacing out a specific interval

o = np.linspace(0, 4, 9)
print(o)

# syntax : (start, stop,  no_of_intervals_to_divide_into)
# note that it is LINspace and not LINEspace

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4. ]


In [32]:
z = np.zeros((2,3))
o = np.ones((2,3))
i = np.eye(3)

print(z)
print(o)
print(i)
#creating a numpy array of zeroes, ones and identity matrices
#note zeros and not ZEROES

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [33]:
n1 = np.array([1,2,3]*3)
print(n1)

#is not exactly same as

n2 = np.repeat([1,2,3], 3)
print(n2)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [9]:
# vstack and hstack for stacking arrays vertically and horizontally respectively
import numpy as np
p = np.ones([2,3], int)
print(p)

print("-----------And now, vertical----------")

p = np.vstack([p, 2*p])
print(p)

print("---------------And now, horizontal-----------------")

p = np.hstack([p, 2*p])
print(p)

[[1 1 1]
 [1 1 1]]
-----------And now, vertical----------
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
---------------And now, horizontal-----------------
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 4 4 4]
 [2 2 2 4 4 4]]


## Numpy arithmetic operations 

We can use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [14]:
# suppose x and y be 2 matrices
m = [1,2,3]
n = [4,5,6]

x = np.array(m)
y = np.array(n)

print(x + y)
print(x - y)

[5 7 9]
[-3 -3 -3]


In [16]:
print(x*y)
print(x/y)

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [21]:
# the matrix scalar multiplication is the same here, just notice the syntax usage

x.dot(y)



32

In [27]:
# and so is the transpose operations involved

z = np.array([y, y**2])
print(z)

print("--------- After the effects-------------")

print(z.T)

print(z.T.shape)

print(z.shape)

[[ 4  5  6]
 [16 25 36]]
--------- After the effects-------------
[[ 4 16]
 [ 5 25]
 [ 6 36]]
(3, 2)
(2, 3)


In [32]:
print(x)

print(x.sum())

print(x.mean())

print(x.std())


# argmax and argmin return the index of the minimum and maximum elements

print(x.argmax())

print(x.argmin())

[1 2 3]
6
2.0
0.816496580928
2
0


Indexing and slicing examples

General Syntax : array[start:stop:stepsize]

Providing all the parameters is optional(U may leave some or all, if u want)

In [34]:
r = np.arange(36)

print(r)

r.resize(6,6)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [45]:
print(r[2,2])

print("------------------")

print(r[3:])

print("------------------")

print(r[3, 3:6])

print("------------------")

print(r[-1, ::2])

# recall step of the syntax, that is used over here

14
------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
------------------
[21 22 23]
------------------
[30 32 34]


### Extra features and iterations

In [62]:
# generating a randomly generated array of integers
# Syntax : (start, stop(excluding this), (order of matrix formed))
i1 = np.random.randint(0,10, (4,4))
print(i1)

[[9 8 7 4]
 [5 4 9 6]
 [9 0 7 8]
 [6 6 6 1]]


In [64]:
#iterate by row and index

for i, r in enumerate(i1):
    print(i,  "is the row", r)

0 is the row [9 8 7 4]
1 is the row [5 4 9 6]
2 is the row [9 0 7 8]
3 is the row [6 6 6 1]


In [67]:
# zip is used for multiple iterations

i2 = i1**2

for i, j in zip(i1, i2):
    print(i, "+" ,j, "=", i+j)

[9 8 7 4] + [81 64 49 16] = [90 72 56 20]
[5 4 9 6] + [25 16 81 36] = [30 20 90 42]
[9 0 7 8] + [81  0 49 64] = [90  0 56 72]
[6 6 6 1] + [36 36 36  1] = [42 42 42  2]
